---
title: "connect_database"
author: "Jon Peder Lindemann"
date: "2/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Create new database
source("functions/newDatabase.R")
newDatabase("tmu_collection.db")
```

# Add a new dataset
```{r}
tmu_db <- dbConnect(SQLite(),"tmu_collection.db") # Connect to database
source("functions/addDataset.R")
addDataset(tmu_db, datasetName = "Entomology collection, UiT Tromsø Museum", collectionCode = "TSZ", institutionCode = "TMU", rightsHolder = "Tromsø University Museum")
dbDisconnect(tmu_db)
```

# Add a new project
```{r}
tmu_db <- dbConnect(SQLite(),"tmu_collection.db") # Connect to database
source("functions/addPrj.R")
addPrj(tmu_db, projectTitle = "Exechia_determinations", projectOwner = "Jon Peder Lindemann", projectStartDate = "2021-07-03")
dbDisconnect(tmu_db)
```

# Add new collecting events
```{r}

tmu_db <- dbConnect(SQLite(),"tmu_collection.db") # Connect to database
colev <- read.table("data/Collecting_events", sep = "\t", header = TRUE, encoding = "UTF-8") # load data

# Remove whitespaces at begining and ends of strings
for (i in 1:ncol(colev)) {
  colev[,i] <- trimws(colev[,i])
}


source("functions/addEvents.R") # load function

# populate collecting events from table
addEvents(tmu_db, 
           eventID = colev$eventID,
           country = colev$country,
           stateProvince = colev$stateProvince,
           county = colev$county,
           strand_id = colev$strand_id,
           municipality = colev$municipality, 
           locality_1 = colev$locality_1, 
           locality_2 = colev$locality_2, 
           habitat = colev$habitat, 
           decimalLatitude = colev$decimalLatitude, 
           decimalLongitude = colev$decimalLongitude, 
           coordinateUncertaintyInMeters = colev$coordinateUncertaintyInMeters, 
           samplingProtocol = colev$samplingProtocol, 
           eventDate_1 = colev$eventDate_1, 
           eventDate_2 = colev$eventDate_2, 
           recordedBy = colev$recordedBy
          )
dbDisconnect(tmu_db)

# Populate from single event
latlon = c(69.685433, 18.951323)
strandkode <- strandr::strandr(lat = latlon[1], lon = latlon[2])
addEvents(tmu_db, 
          eventID = "JPL_A209", 
          county = "Troms og Finnmark",
          strand_id = "TRI",
          municipality = "Storfjord", 
          locality_1 = "Skibotndalen",
          locality_2 = "Bærfjellet", 
          decimalLatitude = "69.31782",
          decimalLongitude = "20.38607", 
          coordinateUncertaintyInMeters = "10", 
          samplingProtocol = "mt",
          eventDate_1 = "2019-06-01",
          eventDate_2 = "2019-07-03", 
          #eventRemarks = "",
          habitat = "Pupulus/Pinus forest",
          recordedBy = "Jon Peder Lindemann"
          )
dbDisconnect(tmu_db)

```

# Add new or update occurrences or taxon names
```{r}
tmu_db <- dbConnect(SQLite(),"tmu_collection.db")
occ <- read.table("data/Occurrences.txt", sep = "\t", header = TRUE, encoding = "UTF-8")
# Remove whitespaces at begining and ends of strings
for (i in 1:ncol(occ)) {
  occ[,i] <- trimws(occ[,i])
}

# populate Occurrences from table
source("functions/addOccurrences.R")
addOccurrences(tmu_db, 
                occurrenceID = "TSZ-JPL-d6032284-e3a2-11e9-8e02-03ce3011d93e",
                eventID = "",
                scientificName = "Exechia lundstroemi Landrock, 1923",
                taxonRank = "species", order = "Diptera", family = "Mycetophilidae", identifiedBy = "Jon Peder Lindemann", sex = "male",
                ownerInstitutionCode = "TMU")

# populate occurrences with catalog number
addOccurrences(tmu_db, 
                occurrenceID = sapply(1:7, uuid::UUIDgenerate),
                catalogNumber = paste("TSZD-JPL-", seq(from = 100100, length.out = 7), sep = ""),
                eventID = "JPL_A194", 
                identifiedBy = "Jon Peder Lindemann",
                scientificName = "Exechia neorepanda", 
                family = "Mycetophilidae", 
                order = "Diptera", 
                taxonRank = "spnov",
                sex = "", 
                ownerInstitutionCode = "TMU")


dbDisconnect(tmu_db)
```

# Populate occurrences with qr-label data
```{r}
source("functions/qrImport.R")
qrImport(tmu_db, qr_data = scan, identifiedBy = "Jon Peder Lindemann", projectTitle = "Duty_work")
```

# Write specimen labels
```{r}
source("functions/insectLabels.R")
sysfonts::font_add_google("Quicksand", "quick")
showtext::showtext_auto()
sysfonts::font.families()

# Plot labels
insectLabels(tmu_db, c("JPL_A119"), n = 3, filename = "bombus.pdf", type = "medium", font_family = "quick")

source("functions/catalogLabels.R")
catalogLabels(tmu_db, catalogNumber = paste("TSZD-JPL-", seq(from = 100100, length.out = 7), sep = ""), filename = "exechia_neorepanda.pdf", type = "type", font_family = "quick")


```


# Write det. labels
```{r}
source("functions/detLabels.R")
detLabels(tmu_db, scientificName = c("Diptera", "Hymenoptera", "Symphyta", "Mycetophilidae"), taxonRank = c("order", "order", "infraorder", "family"), order = c("Diptera", "Hymenoptera", "Hymenoptera", "Diptera"), family = c("", "", "", "Mycetophilidae"), filename = "higher.pdf", owner_code = "TMU", add_taxa = TRUE, setup = "higher")
```

export to simple darwin core xml file
```{r}
source("functions/simpleExport.R")
test <- simpleExport(CONN = tmu_db, file_name = "test", rank = "species",  new_records = FALSE, write_simple_dwc = TRUE, write_dwc_archive = TRUE, datasetName = "Pteromalidae Norway")
```

Add occurrences to a project
```{r}
source("functions/alterPrjOcc.R")
alterPrjOcc(tmu_db, projectTitle = "Duty_work", occurrenceID = test)
```
Show occurrences in project
```{r}
source("functions/prjOcc.R")
test2 <- prjOcc(tmu_db, projectTitle = "Duty_work")
length(unique(test2))
```


Change value in a table
```{r}
dbExecute(tmu_db, "update Collecting_events set recordedBy='' where recordedBy='Rita Stenersen'")
```

